### ISSUE TITLE
Doesn't work with nuxt

### ISSUE THREAD

**Issue by laSinteZ** [mhayes/vue-twentytwenty#10]
## Description
`vue-twentytwenty` doesn't work out-of-a-box with `Nuxt.js`. My guess is because component is a provided is exported from the package "as-is" without any installation script, even though https://github.com/mhayes/vue-twentytwenty/blob/master/vue-twentytwenty.js is in the repository.

Even though I've found a workaround, it might be a good idea to include such usecase by default (or maybe mention solution in readme).

## How to reproduce
1. Create empty nuxt repo
2. Install vue-twentytwenty as described here.
I can provide a demo repo if required :)

## Solution
Use it as nuxt-plugin.
https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-353827607
I've created a plugin with
```
import Vue from 'vue';
import TwentyTwenty from 'vue-twentytwenty';

Vue.component('twenty-twenty', TwentyTwenty);
```
And it works like a charm :)

**Comment by simoroma** [comment]
Could you help me out with this? When I create a plugin I get the following error:
```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'component')                         12:20:09
  at ./node_modules/vue-twentytwenty/dist/vue-twentytwenty.common.js:449:55  
  at ./node_modules/vue-twentytwenty/dist/vue-twentytwenty.common.js:457:2  
  at Object.<anonymous> (./node_modules/vue-twentytwenty/dist/vue-twentytwenty.common.js:459:12)  
  at Module._compile (node:internal/modules/cjs/loader:1191:14)  
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)  
  at Module.load (node:internal/modules/cjs/loader:1069:32)  
  at Function.Module._load (node:internal/modules/cjs/loader:904:12)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)  
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I added in `nuxt.config.ts`:
```
export default defineNuxtConfig({
    app: {
        build: {
            vendor: ['vue-twentytwenty'],
            plugins: [{ src: '~/plugins/vue-twentytwenty', ssr: false }],
        },
    },
});
```
